extpipes:
  features:
    # naming-pattern: used for name generation bases on metadata fields. Useful with established naming convention
    # notation: jinja2 template. each variable is a respective metadata key
    naming-pattern: "{{source}}:{{table_name}}:some-suffix"

    # new since v2.1.0
    # changed: default to false in v3
    # The default and recommended value is: false
    # to keep the deployment in sync with configuration
    # which means non-configured extpipes can get automatically deleted
    automatic-delete: false

    # new since v3.0.1 (merged with pipeline-level contacts)
    # can contain multiple contacts, will be populated in addition to the pipeline level
    default-contacts:
      - name: Yours Truly
        email: yours.truly@cognite.com
        role: admin
        send-notification: false

  pipelines:
      # optional, requires naming-pattern provided if omitted
    - external-id: src:001:sap:sap_funcloc:continuous
      # optional, requires naming-pattern provided if omitted
      name: src:001:sap:sap_funcloc:continuous
      # optional
      description: describe or defaults to auto-generated description, that it is "deployed through extpipes-cli@v3.0.0"
      # optional, for deployments w/o full scoping?
      data-set-external-id: src:001:sap
      # optional: string or null^(On trigger|Continuous)|(@(annually|yearly|monthly|weekly|daily|hourly|reboot))|(@every (\d+(ns|us|µs|ms|s|m|h))+)|((((\d+,)+\d+|(\d+([/\-])\d+)|\d+|\*(/\d+)?) ?){5,7})$
      # "On trigger", "Continuous" or cron expression
      schedule: Continuous
      # optional [{},{}]
      # defaults to features.default-contacts (if exist)
      contacts:
        - name: Fizz Buzz
          email: fizzbuzz@cognite.com
          role: admin
          send-notification: true
      # optional
      source: az-func
      # optional {}
      metadata:
        version: extpipes-cli@v3.1.0
      # optional max 10000 char
      # Documentation text field, supports Markdown for text formatting.
      # TODO: simple option to link to another file in yaml? 10k can be quite long?!
      documentation: Documentation which can include Mermaid diagrams?
      # optional
      # Usually user email is expected here, defaults to extpipes + version?
      created-by: extpipes-cli@v3.1.0

      # optional, defaults to empty list []
      raw-tables:
        - db-name: src:001:sap
          table-name: sap_funcloc

      # optional {}
      # exactly one
      # https://docs.cognite.com/api/v1/#tag/Extraction-Pipelines-Config/operation/createExtPipeConfig
      extpipe-config:
        # str
        # TODO: only push it to CDF if changed since last time, otherwise it will create a new revision
        config: |
          nested yaml/json/ini which is simply a string for this config
        # optional
        # TODO: which length limit?
        description: describe the config, or autogenerate?
        # TODO: officially optional, but in extpipes it should be mandatory
        # TODO: length limit?

# follows the same parameter structure as the DB extractor configuration
cognite: # kwargs to pass to the CogniteClient, Environment variable format: ${ENVIRONMENT_VARIABLE}
  host: https://${HOST}
  project: ${PROJECT}
  idp-authentication:
    client-id: ${CLIENT_ID}
    secret: ${CLIENT_SECRET}
    scopes:
      - https://${HOST}/.default
    token_url: ${TOKEN_URL}

# https://docs.python.org/3/library/logging.config.html#logging-config-dictschema
# https://docs.python.org/3/howto/logging-cookbook.html
logging:
  version: 1
  formatters:
    formatter:
      format: "[%(asctime)s] [%(levelname)s] [%(name)s]: %(message)s"
  handlers:
    file:
      class: "logging.FileHandler"
      filename: ./logs/deploy-trading.log
      formatter: "formatter"
      mode: "w"
      level: "INFO"
    console:
      class: "logging.StreamHandler"
      level: "INFO"
      formatter: "formatter"
      stream: "ext://sys.stderr"
  root:
    level: "INFO"
    handlers: ["console", "file"]
  loggers:
    cognite-sdk:
      level: "INFO"
      handlers: ["console"]
