name: Code Quality checks for PRs

on:
  pull_request:

jobs:
  checks:
    name: Pre-Commit checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Set up cache
        uses: actions/cache@v2.1.6
        with:
          path: .venv
          key: venv-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('poetry.lock') }}

      - name: Install Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true
          poetry build
          poetry install

      - name: Cache Linting Installation
        uses: actions/cache@v2.1.6
        with:
          path: ~/.cache/pre-commit
          key: venv-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('poetry.lock') }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run linting
        run: |
          poetry run pre-commit run --all-files

      # - name: Run tests
      #  run: poetry run pytest -m "not integration"
